version: "3.9"

services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile.api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - db
      - cache
  web:
    build:
      context: ../
      dockerfile: Dockerfile.web
    ports:
      - "5173:5173"
    depends_on:
      - api
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: avook
      POSTGRES_PASSWORD: avook
      POSTGRES_DB: avook
    ports:
      - "5432:5432"
  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - api
      - web
