"""add image_path to qr_codes table

Revision ID: 626bed6b1f13
Revises: e1b8b7e70462
Create Date: 2025-09-04 22:02:14.017333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626bed6b1f13'
down_revision: Union[str, Sequence[str], None] = 'e1b8b7e70462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_codes', 'image_path')
    # ### end Alembic commands ###
