name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Display message
        run: echo "CI pipeline will be implemented in future iterations."
